In [23]:
import numpy as np
from scipy import linalg as la

In [3]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [5]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a = np.array([1,3,6,9])
b = np.linspace(0,9,4) # 0到9之間分4等分
b

array([0., 3., 6., 9.])

In [11]:
c = a - b
c

array([1., 0., 0., 0.])

In [18]:
a**2

array([ 1,  9, 36, 81], dtype=int32)

In [32]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.transpose()


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [33]:
np.array(a).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
v1=la.inv(a)
v1

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [41]:
c = np.random.rand(3,3)
c

array([[0.87618043, 0.58776485, 0.40476334],
       [0.29850391, 0.42640977, 0.36258518],
       [0.80907204, 0.76166048, 0.8322711 ]])

In [42]:
np.dot(a,c)

array([[ 3.90040437,  3.72556584,  3.62674699],
       [ 9.85167351,  9.05307116,  8.42560585],
       [15.80294265, 14.38057648, 13.2244647 ]])

In [50]:
z = np.zeros((3,2),np.uint8)
type(z)

numpy.ndarray

In [51]:
z

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=uint8)

In [53]:
o = np.ones((2,4),np.int32)
o

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [55]:
m = np.array([[2,12,3,1],[10,12,14,29],],np.float32)
m


array([[ 2., 12.,  3.,  1.],
       [10., 12., 14., 29.]], dtype=float32)

In [62]:
print(m.shape)
print(m.dtype)

(2, 4)
float32


In [63]:
m = np.array([[[1,2,3,4],[5,6,7,8]],[[10,11,12,14],[15,16,17,18]]],np.float32)
m

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[10., 11., 12., 14.],
        [15., 16., 17., 18.]]], dtype=float32)

In [72]:
m = np.array([[14,12,3,1],[10,12,114,29],[67,23,534,2]],np.float32)
m

array([[ 14.,  12.,   3.,   1.],
       [ 10.,  12., 114.,  29.],
       [ 67.,  23., 534.,   2.]], dtype=float32)

In [69]:
m[1,3]

29

In [73]:
m[:,2]

array([  3., 114., 534.], dtype=float32)

In [74]:
m[1,:]

array([ 10.,  12., 114.,  29.], dtype=float32)

In [75]:
m[0:2,1:3]

array([[ 12.,   3.],
       [ 12., 114.]], dtype=float32)

In [76]:
m = np.array([[[1,2,3,4],[5,6,7,8]],[[10,11,12,14],[15,16,17,18]],[[11,12,43,32],[1,5,10,23]]],np.float32)
m

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[10., 11., 12., 14.],
        [15., 16., 17., 18.]],

       [[11., 12., 43., 32.],
        [ 1.,  5., 10., 23.]]], dtype=float32)

In [79]:
m[:,:,0]

array([[ 1.,  5.],
       [10., 15.],
       [11.,  1.]], dtype=float32)

In [80]:
m[0,:,:]

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)

In [82]:
m[:,1,:]

array([[ 5.,  6.,  7.,  8.],
       [15., 16., 17., 18.],
       [ 1.,  5., 10., 23.]], dtype=float32)

In [83]:
src1 = np.array([[23,123,90],[100,250,0]],np.uint8)
src2 = np.array([[125,150,60],[100,10,40]],np.uint8)
dst = src1 + src2
dst

array([[148,  17, 150],
       [200,   4,  40]], dtype=uint8)

In [91]:
import cv2
dst = cv2.add(src1,src2, dtype=cv2.CV_32F)
dst

array([[148., 273., 150.],
       [200., 260.,  40.]], dtype=float32)

In [94]:
src2 = np.array([[125,150,60],[100,10,40]],np.uint8)
dst = src1 - src2
dst

array([[154, 229,  30],
       [  0, 240, 216]], dtype=uint8)

In [96]:
src2 = np.array([[125,150,60],[100,10,40]],np.float32)
dst = src1 * src2
dst

array([[ 2875., 18450.,  5400.],
       [10000.,  2500.,     0.]], dtype=float32)

In [97]:
dst = np.multiply(src1, src2)
dst

array([[ 2875., 18450.,  5400.],
       [10000.,  2500.,     0.]], dtype=float32)

In [99]:
src2 = np.array([[125,150,60],[100,10,40]],np.uint8)
dst = src2 / src1
dst

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[5.43478261, 1.2195122 , 0.66666667],
       [1.        , 0.04      ,        inf]])

In [102]:
src3 = np.array([[1,2,3],[4,5,6]],np.uint8)
src4 = np.array([[6,5],[4,3],[2,1]],np.uint8)
dst = np.dot(src3, src4)
dst

array([[20, 14],
       [56, 41]], dtype=uint8)

In [103]:
src5 = np.array([[6,5],[4,3]],np.uint8)
dst2 = np.log(src5)
dst2.dtype


dtype('float16')

In [104]:
src = np.array([[30,40],[10,100]],np.uint8)
dst1 = np.power(src,2)
dst1

array([[132,  64],
       [100,  16]], dtype=uint8)

In [105]:
dst2 = np.power(src, 2.0)
dst2

array([[  900.,  1600.],
       [  100., 10000.]])